apiVersion: v1
kind: Pod 
metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend
spec:
  containers:
    - name: nginx
      image: nginx

      # kubectl create/apply -f pod.yml
      # kubectl get pods
      # kubectl describe pod nginx
